# Generated by Django 4.2.13 on 2026-10-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0049_alter_petition_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='petitiontemplate',
            name='paper_signatures',
            field=models.IntegerField(default=0),
        ),
    ]
