# Generated by Django 4.2.30 on 2026-10-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0050_petitiontemplate_paper_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='newsletter_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signature',
            name='notice_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='ipaddress',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['confirmation_hash'], name='sig_conf_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['petition', 'confirmed', 'email'], name='sig_pet_conf_email_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['petition', 'date'], name='sig_pet_date_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['confirmed', 'date'], name='sig_conf_date_idx'),
        ),
        migrations.AddIndex(
            model_name='signature',
            index=models.Index(fields=['petition', 'ipaddress', 'date'], name='sig_pet_ip_date_idx'),
        ),
    ]
